Changes related to SECCOMP configuration and Rust Inline Filter.

diff --git a/src/test_utils/scripts/ansible/local-store-pub-sub-tests-rust.yml b/src/test_utils/scripts/ansible/local-store-pub-sub-tests-rust.yml
--- a/src/test_utils/scripts/ansible/local-store-pub-sub-tests-rust.yml
+++ b/src/test_utils/scripts/ansible/local-store-pub-sub-tests-rust.yml
@@ -19,40 +19,39 @@
       killall -9 jal-local-store || true
       killall -9 jal_subscribe || true
       killall -9 jaldb_inline_filter || true
-      killall -9 jald_marker || true
       killall -9 jald || true
       #rm -f {{cwd}}/jald_record_socket
       rm -f {{cwd}}/jald_filter_socket*
       rm -f {{cwd}}/*.sock
-  
+
   - name: clear local store database
     file:
         path: '{{cwd}}/testdb'
         state: absent
-  
+
   - name: clear subscriber database
     file:
         path: '{{cwd}}/subdb'
         state: absent
-  
+
   - name: make local store database directory
     file:
         path: '{{cwd}}/testdb'
         state: directory
-  
+
   - name: make subscriber database directory
     file:
         path: '{{cwd}}/subdb'
         state: directory
-  
+
   - name: copy DB_CONFIG 1
-    copy: 
+    copy:
         mode: 0640
         src:  '{{cwd}}/test-input/LMDB_CONFIG'
         dest: '{{cwd}}/subdb'
-  
+
   - name: copy DB_CONFIG 2
-    copy: 
+    copy:
         mode: 0640
         src:  '{{cwd}}/test-input/LMDB_CONFIG'
         dest: '{{cwd}}/testdb'
@@ -60,7 +59,7 @@
   - name: pre-sleep
     shell: |
       sleep {{ pre_sleep }}
-  
+
   - name: start local store
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
@@ -69,21 +68,12 @@
       umask 027
       ./{{mode}}/bin/jal-local-store -c ./test-input/local_store.cfg --no-daemon 2>./ls.err 1>./ls.out &
 
-  - name: start CPP marker
-    environment:
-      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
-    shell: |
-      cd '{{cwd}}'
-      #gdb -batch -ex "run" -ex "bt" --args ./{{mode}}/bin/jald_marker -c ./test-input/jald_marker.cfg 2>./jald_marker.err 1>./jald_marker.out &
-      ./{{mode}}/bin/jald_marker -c ./test-input/jald_marker.cfg 2>./jald_marker.err 1>./jald_marker.out &
-    when: marker == 'cpp'
-
   - name: start Rust marker ({{marker_bin}}/jaldb_inline_filter)
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
     shell: |
       cd '{{cwd}}'
-      RUST_LOG={{rust_log}} {{marker_bin}}/jaldb_inline_filter -d {{cwd}}/testdb --force --rx-socket-path "./jald_filter_socket_request" --tx-socket-path "./jald_filter_socket" 2>./jaldb_inline_filter.err 1>./jaldb_inline_filter.out &
+      RUST_LOG={{rust_log}} {{marker_bin}}/jaldb_inline_filter -c ./test-input/jaldb-filter.toml -d {{cwd}}/testdb 2>./jald_filter.err 1>./jald_filter.out &
     when: marker == 'rust'
 
   - name: start subscriber
@@ -92,14 +82,14 @@
     shell: |
       cd '{{cwd}}'
       ./{{mode}}/bin/jal_subscribe -c ./test-input/jal_subscribe.cfg -d 2>./subd.err 1>./subd.out &
-    
+
 #  - name: check subscriber database directory exists
 #    stat:
 #        path: '{{cwd}}/subdb/lock.mdb'
 #    register: subscriber_stat
-#    
+#
 #  - name: Fail if file does not exists
-#    fail: 
+#    fail:
 #      msg: 'jal_subscriber did not start correctly'
 #    when: subscriber_stat.stat.exists == False
 
@@ -117,18 +107,18 @@
   - name: send logs
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
-        #async: "{{ max_send_time }}"
-        #poll: 0
+    async: "{{ max_send_time }}"
+    poll: 0
     command:
         chdir: '{{cwd}}'
         cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t l'
     when: '"l" in types'
-  
+
   - name: send journals
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
-        #async: "{{ max_send_time }}"
-        #poll: 0
+    async: "{{ max_send_time }}"
+    poll: 0
     command:
         chdir: '{{cwd}}'
         cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t j'
@@ -137,8 +127,8 @@
   - name: send journals FDs
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
-        #async: "{{ max_send_time }}"
-        #poll: 0
+    async: "{{ max_send_time }}"
+    poll: 0
     command:
         chdir: '{{cwd}}'
         cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t f'
@@ -147,8 +137,8 @@
   - name: send audits
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
-        #async: "{{ max_send_time }}"
-        #poll: 0
+    async: "{{ max_send_time }}"
+    poll: 0
     command:
         chdir: '{{cwd}}'
         cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t a'
@@ -156,7 +146,9 @@
 
   - name: sleep
     shell: |
-      #sleep 20
+      killall -9 jald || true
+      # killall -9 jal_subscribe || true
+      # sleep 20
       PID=`/usr/sbin/pidof ./{{mode}}/bin/jald`
       (( cpu="10" ))
       (( retry_count=0 ))
@@ -186,7 +178,7 @@
         cmd: ./{{mode}}/bin/jaldb_tool -h testdb
     register: jaldb_tool_testdb_output
     when: tear_down | bool
-    
+
   - name: jaldb_tool subdb
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
@@ -195,7 +187,7 @@
         cmd: ./{{mode}}/bin/jaldb_tool -h subdb
     register: jaldb_tool_subdb_output
     when: tear_down | bool
-        
+
   - name: jaldb_tool output
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
@@ -213,7 +205,7 @@
       ./{{mode}}/bin/jaldb_tail -h testdb/ -t l|grep -P -m 1 '\dT\d'|sed 's/_.*//'|sed 's/\s//'
     register: jaldb_tail_output
     when: tear_down | bool
-    
+
   - name: jal_dump
     environment:
       LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
@@ -222,27 +214,27 @@
       ./{{mode}}/bin/jal_dump -h testdb/ -u '{{ jaldb_tail_output.stdout }}' -d m -t l
     register: jal_dump_output
     when: tear_down | bool
-  
+
   - name: jal_dump output
     shell: |
       cd '{{cwd}}'
       echo '{{ jal_dump_output.stdout }}' >> jaldb_tool_output.txt
     when: tear_down | bool
-      
+
   - name: end processes
     shell: |
       killall jal-local-store || true
+      killall jald || true
+      sleep 2
       killall jal_subscribe || true
       killall jaldb_inline_filter || true
-      killall jald_marker || true
-      killall jald || true
       rm -f {{cwd}}/jald_record_socket_*
-      rm -f {{cwd}}/jald_filter_socket
+      rm -f {{cwd}}/jald_filter_socket*
       rm -f {{cwd}}/*.sock
     when: tear_down | bool
-     
+
   - name: build cov report
-    shell: |      
+    shell: |
       cd '{{cwd}}'
       echo '{{cwd}}' >> jaldb_tool_output.txt
       mkdir cov_integration
